-- Put the bond and crypto ETFs in the classes they belong to.
--
-- Asset class had never been load-bearing: it coloured a donut of what is
-- held today, and the positions this corrected were all closed. Splitting net
-- worth by class month by month makes it history, and the history was wrong --
-- bond funds filed as US equity, so the Bonds band read empty for a portfolio
-- that held bonds; and exchange-traded crypto funds filed by the account they
-- sit in rather than the exposure they carry.
--
-- The correction itself is deliberately not here. It was a list of one
-- person's holdings, and a migration runs on every deployment, so shipping it
-- would install those symbols into every database that ever applies it. A
-- fresh database has no rows to reclassify, which is why this can be empty
-- rather than conditional.
--
-- To correct an existing install, reclassify by hand on the investments page,
-- or with a local script that takes its symbols as arguments.
SELECT 1;
