#!/bin/sh
# Rebuild the private deny-list from the database this installation actually holds.
#
# The guard has always been able to reject a list of forbidden terms, and the
# list has always been maintained by hand -- which means it was maintained
# never. A comment naming a real holding passed every check because that ticker
# had never been typed into the list, and nobody thinks to add a ticker to a
# deny-list at the moment they are writing prose about it.
#
# So the list is derived instead — from the parts of the database that identify
# a person rather than a market: account and institution names, and the payees
# off their statement. Tickers are deliberately left out: a symbol is public,
# and blocking the ones this person happens to hold only makes the fixtures
# worse, since real symbols are what cover the edge cases the app must handle.
#
#   DATABASE_URL=... scripts/refresh-private-terms.sh
#
# Writes to ~/.config/aurum/private-terms.txt (override with AURUM_PRIVATE_TERMS).
# The destination is outside the repository on purpose -- a list of someone's
# holdings committed to their own repository is the disclosure it exists to
# prevent -- and this script writes nothing back into the tree.
set -eu

OUT="${AURUM_PRIVATE_TERMS:-$HOME/.config/aurum/private-terms.txt}"
CONTAINER="${AURUM_DB_CONTAINER:-finance-db-1}"
DB="${AURUM_DB:-aurum}"
DBUSER="${AURUM_DB_USER:-aurum}"

query() {
  docker exec "$CONTAINER" psql -U "$DBUSER" -d "$DB" -At -c "$1" 2>/dev/null || true
}

mkdir -p "$(dirname "$OUT")"
tmp="$OUT.tmp.$$"

{
  echo "# Generated by scripts/refresh-private-terms.sh -- do not edit by hand."
  echo "# Every term here is a fact about this installation, taken from its own"
  echo "# database. Re-run after adding an account or a holding."
  echo "#"
  echo "# Add anything the database does not know below the marker at the end:"
  echo "# the machine's hostname, a lender, people named in a shared expense."
  echo

  # Deliberately NOT the tickers, nor the security names behind them.
  #
  # A symbol is public: anyone can look up what MSFT is, and blocking the ones
  # this person happens to hold makes the test fixtures worse — real symbols are
  # what cover the edge cases the app has to handle, a receipt beside its
  # underlying, a venue suffix, a coin. What is private is the *combination*:
  # the holding with its size, its cost and its account attached. Amounts and
  # export rows are caught by the patterns in the guard, which is where that
  # belongs.
  #
  # What is left here is what genuinely identifies a person rather than a
  # market: where they bank, what their accounts are called, and who they pay.
  query "SELECT DISTINCT name FROM accounts WHERE name <> '' AND name <> '—'"
  query "SELECT DISTINCT institution FROM accounts WHERE institution <> '' AND institution <> '—'"

  # Merchants and counterparties off the statement. A payee names a person's
  # habits, their landlord, their lender — and unlike a ticker it is not a
  # public fact about a market.
  #
  # Excluding any payee that is really a category name. The monthly spreadsheet
  # import writes the category into the payee column, so "Groceries", "Interest"
  # and "Dividends" arrive here looking like merchants — and they are the app's
  # own vocabulary, printed in a dozen source files. Blocking those would make
  # the guard fire on ordinary code, and a guard that always fires gets switched
  # off.
  query "SELECT DISTINCT t.payee FROM transactions t
           WHERE t.payee <> '' AND length(t.payee) > 4
             AND NOT EXISTS (SELECT 1 FROM categories c WHERE lower(c.name) = lower(t.payee))
             AND lower(t.payee) NOT IN (
               SELECT lower(category) FROM transactions
             )"
} | tr -d '\r' \
  | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' \
  | grep -v '^$' \
  | sort -uf > "$tmp.raw"

# Terms too short or too common to block on. "CAD", "USD" and single letters
# would fire on every file in the repository, and a guard that always fires is
# one that gets switched off.
#
# Two kinds of exclusion. Currencies, plan names and corporate suffixes are too
# common to block on -- a guard that fires on every file is one that gets
# switched off. And a few symbols are things the product itself has to name:
# the benchmark it charts against, and the major coins its asset-class
# detection tests for. Holding those does not make the app unable to mention
# them; blocking them would make `isCoinTicker` unwritable.
# Payees this app writes itself.
#
# A circular match, and a subtle one: the importer labels a broker row "Cash
# back" or "Margin interest", that label lands in the payee column, the list is
# derived from payees, and the guard then refuses to let the source contain the
# very string the source produces. These name the broker's export format, which
# the parser has to name to read it — they say nothing about whose statement it
# was.
APP_PAYEES='Cash back|Bonus|Margin interest|Withholding tax|Interest|Interest & cashback|Pension|Net pay|Deposit|Withdrawal|Rent'
# The bank's and broker's own words for a row. The parser has to contain them to
# recognise them, and they describe a transaction type rather than a person.
FORMAT_WORDS='Interac e-Transfer® Out|Interac e-Transfer® Received|Direct deposit received|Pre-authorized Debit|Credit card payment|Cash sent|Giveaway received|Spend'

STOP='^(CAD|USD|TFSA|RRSP|FHSA|Pension|Cash|Chequing|Savings|Inc|Inc\.|The|and|of|ETF|Portfolio|Class|A|B|BTC|ETH|SOL|XEQT|XEQT\.TO|Non-registered|non-registered|Margin|margin)$'
# Retail chains the app already recognises are public businesses, not personal
# counterparties, and the same reasoning applies to them as to a ticker: anyone
# can look up what Canadian Tire is. What identifies a person is who they owe —
# a lender, a landlord, a servicer, an individual — which the app's keyword
# lists do not contain and never will.
#
# Taken from those lists rather than typed here, so the two cannot drift: if
# the matcher learns a chain, the deny-list stops blocking it in the same
# breath.
CHAINS="$tmp.chains"
sed -n '/^  \["/,/^\]/p' src/lib/csv.ts 2>/dev/null \
  | grep -oE '"[^"]{4,}"' | tr -d '"' | tr 'A-Z' 'a-z' \
  | sort -u > "$CHAINS" || : > "$CHAINS"

awk 'length($0) >= 3' "$tmp.raw" \
  | grep -Evi "$STOP" \
  | grep -Evxi "$APP_PAYEES" \
  | grep -Evxi "$FORMAT_WORDS" \
  | { if [ -s "$CHAINS" ]; then grep -ivFf "$CHAINS"; else cat; fi } > "$tmp"
rm -f "$CHAINS"
rm -f "$tmp.raw"

# Anything hand-added last time, kept.
MARK="# ---- added by hand below this line ----"
if [ -f "$OUT" ] && grep -qF "$MARK" "$OUT"; then
  sed -n "/$(printf '%s' "$MARK" | sed 's/[]\/$*.^[]/\\&/g')/,\$p" "$OUT" >> "$tmp"
else
  { echo; echo "$MARK"; } >> "$tmp"
fi

mv "$tmp" "$OUT"
chmod 600 "$OUT"
printf 'Wrote %s terms to %s\n' "$(grep -cv '^[#[:space:]]*$' "$OUT")" "$OUT"
