#!/bin/sh
# Rebuild the private deny-list from the database this installation actually holds.
#
# The guard has always been able to reject a list of forbidden terms, and the
# list has always been maintained by hand -- which means it was maintained
# never. A comment naming a real holding passed every check because that ticker
# had never been typed into the list, and nobody thinks to add a ticker to a
# deny-list at the moment they are writing prose about it.
#
# So the list is derived instead. Every ticker held, every account and
# institution name, every payee the record knows: if it is in the database it is
# a fact about this person, and it has no business in the source.
#
#   DATABASE_URL=... scripts/refresh-private-terms.sh
#
# Writes to ~/.config/aurum/private-terms.txt (override with AURUM_PRIVATE_TERMS).
# The destination is outside the repository on purpose -- a list of someone's
# holdings committed to their own repository is the disclosure it exists to
# prevent -- and this script writes nothing back into the tree.
set -eu

OUT="${AURUM_PRIVATE_TERMS:-$HOME/.config/aurum/private-terms.txt}"
CONTAINER="${AURUM_DB_CONTAINER:-finance-db-1}"
DB="${AURUM_DB:-aurum}"
DBUSER="${AURUM_DB_USER:-aurum}"

query() {
  docker exec "$CONTAINER" psql -U "$DBUSER" -d "$DB" -At -c "$1" 2>/dev/null || true
}

mkdir -p "$(dirname "$OUT")"
tmp="$OUT.tmp.$$"

{
  echo "# Generated by scripts/refresh-private-terms.sh -- do not edit by hand."
  echo "# Every term here is a fact about this installation, taken from its own"
  echo "# database. Re-run after adding an account or a holding."
  echo "#"
  echo "# Add anything the database does not know below the marker at the end:"
  echo "# the machine's hostname, a lender, people named in a shared expense."
  echo

  # Tickers, and their venue-less form -- a comment is as likely to write MA as
  # MA.NEO, and either one identifies the position.
  query "SELECT DISTINCT ticker FROM holdings WHERE ticker <> ''"
  query "SELECT DISTINCT regexp_replace(upper(ticker), '\.[A-Z]+\$', '') FROM holdings WHERE ticker <> ''"

  # Account and institution names, which name the broker and the plan.
  query "SELECT DISTINCT name FROM accounts WHERE name <> '' AND name <> '—'"
  query "SELECT DISTINCT institution FROM accounts WHERE institution <> '' AND institution <> '—'"

  # Security names: "Mastercard Incorporated (Class A)" identifies as surely as
  # the symbol does. Split to words so a partial mention is caught too.
  query "SELECT DISTINCT name FROM holdings WHERE name <> '' AND name <> ticker"
} | tr -d '\r' \
  | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' \
  | grep -v '^$' \
  | sort -uf > "$tmp.raw"

# Terms too short or too common to block on. "CAD", "USD" and single letters
# would fire on every file in the repository, and a guard that always fires is
# one that gets switched off.
#
# Two kinds of exclusion. Currencies, plan names and corporate suffixes are too
# common to block on -- a guard that fires on every file is one that gets
# switched off. And a few symbols are things the product itself has to name:
# the benchmark it charts against, and the major coins its asset-class
# detection tests for. Holding those does not make the app unable to mention
# them; blocking them would make `isCoinTicker` unwritable.
STOP='^(CAD|USD|TFSA|RRSP|FHSA|Pension|Cash|Chequing|Savings|Inc|Inc\.|The|and|of|ETF|Portfolio|Class|A|B|BTC|ETH|SOL|XEQT|XEQT\.TO)$'
awk 'length($0) >= 3' "$tmp.raw" | grep -Evi "$STOP" > "$tmp"
rm -f "$tmp.raw"

# Anything hand-added last time, kept.
MARK="# ---- added by hand below this line ----"
if [ -f "$OUT" ] && grep -qF "$MARK" "$OUT"; then
  sed -n "/$(printf '%s' "$MARK" | sed 's/[]\/$*.^[]/\\&/g')/,\$p" "$OUT" >> "$tmp"
else
  { echo; echo "$MARK"; } >> "$tmp"
fi

mv "$tmp" "$OUT"
chmod 600 "$OUT"
printf 'Wrote %s terms to %s\n' "$(grep -cv '^[#[:space:]]*$' "$OUT")" "$OUT"
